#!/bin/bash

response=$(curl -s "http://ip-api.com/json")
city=$(echo $response | jq -r '.city')
region=$(echo $response | jq -r '.region')

if [[ "$region" == "DL" ]]; then
    city="New Delhi"
fi

echo "$city"

