#!/bin/bash

api_key="a8535dde24a0b70e79d23adfa90e0519"
city_id=4693342
#city_id=4705708
url="http://api.openweathermap.org/data/2.5/weather?id=${city_id}&appid=${api_key}&units=metric"

response=$(curl -s "$url")
current_temp=$(echo "$response" | jq -r '.main.temp')
echo "$current_temp"

