#!/bin/bash

# Set your API key and city ID
API_KEY="a8535dde24a0b70e79d23adfa90e0519"
CITY_ID="4693342"
#CITY_ID="4705708"

# Make the API request to OpenWeather
response=$(curl -s "http://api.openweathermap.org/data/2.5/weather?id=${CITY_ID}&appid=${API_KEY}")

# Parse the humidity from the JSON response
humidity=$(echo $response | jq -r '.main.humidity')

# Output the humidity
echo "${humidity}%"

