#!/bin/bash

# Scripts for refreshing waybar, rofi, swaync, wallust

SCRIPTSDIR=$HOME/.config/hypr/scripts

# Define file_exists function
file_exists() {
    if [ -e "$1" ]; then
        return 0  # File exists
    else
        return 1  # File does not exist
    fi
}

# Kill already running processes
_ps=(waybar)
#_ps=(waybar rofi swaync wofi)
for _prs in "${_ps[@]}"; do
    pids=$(pgrep -x "${_prs}")
    if [ -n "$pids" ]; then
        echo "Killing ${_prs}..."
        for pid in $pids; do
            kill $pid
        done
        sleep 0.1  # Small delay to ensure process termination
    fi
done

sleep 0.1  # Added sleep to ensure all processes are terminated

# Relaunch waybar
echo "Relaunching waybar..."
waybar -l info -c ~/.config/waybar/config -s ~/.config/waybar/style.css > /tmp/waybar.log 2>&1 &

# Check if waybar was started successfully
sleep 0.1
if pgrep -x waybar > /dev/null; then
    echo "Waybar started successfully."
else
    echo "Failed to start waybar. Check /tmp/waybar.log for details."
fi

# Relaunch swaync
echo "Relaunching swaync..."
swaync > /dev/null 2>&1 &

echo "Script finished."
exit 0

