#!/bin/bash

api_key="a8535dde24a0b70e79d23adfa90e0519"
#city_id=4705708
city_id="4693342"

url="http://api.openweathermap.org/data/2.5/weather?id=${city_id}&appid=${api_key}&units=metric"

response=$(curl -s "$url")
wind_speed_mps=$(echo "$response" | jq -r '.wind.speed')
wind_speed_mph=$(echo "$wind_speed_mps * 2.23694" | bc)
echo "$wind_speed_mph mph"

#wind_speed_kph=$(echo "$wind_speed_mps * 3.6" | bc)
#echo "$wind_speed_kph km/h"
