#!/usr/bin/bash

# Start Policy Authentication Agent
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# Start GNOME Keyring with all components
eval $(gnome-keyring-daemon --start --components=gpg,pkcs11,secrets,ssh)
export SSH_AUTH_SOCK=$XDG_RUNTIME_DIR/gcr/ssh

# Import Wayland and GNOME environment variables and update system dbus
systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
dbus-update-activation-environment --systemd DISPLAY WAYLAND_DISPLAY XDG_CURRENT_DESKTOP --all

# Set paths and other environment variables
scripts=~/.config/hypr/scripts
export PATH=$PATH:$scripts
export XDG_CURRENT_DESKTOP=Hyprland
export XDG_SESSION_TYPE=wayland
export XDG_SESSION_DESKTOP=Hyprland
export QT_QPA_PLATFORM=wayland;xcb
export QT_QPA_PLATFORMTHEME=qt6ct
export QT_WAYLAND_DISABLE_WINDOWDECORATION=1
export QT_AUTO_SCREEN_SCALE_FACTOR=1
export MOZ_ENABLE_WAYLAND=1
export GDK_SCALE=1
export QT_STYLE_OVERRIDE=kvantum
export QT_QPA_PLATFORMTHEME=qt5ct

# Configure GSettings for GTK and GNOME environments
gsettings set org.gnome.desktop.interface gtk-theme 'Tokyonight-Dark-BL-LB'
gsettings set org.gnome.desktop.interface font-name 'Calibri Font 12'
gsettings set org.gnome.desktop.interface icon-theme 'Tokyonight-Moon'
gsettings set org.gnome.desktop.interface cursor-theme 'Sweet-cursors'
gsettings set org.cinnamon.desktop.default-applications.terminal exec kitty

# Launch swaync, notification daemon
swaync &

# Launch Waybar with a script
$scripts/launch_waybar &

# Set wallpaper with a script
$scripts/wallpaper.sh init &

# Start system tray applets
blueman-applet &
nm-applet --indicator &

# Set custom cursor size using hyprctl
hyprctl setcursor Sweet-cursors 24

# Clipboard management
wl-paste --type text --watch cliphist store &
wl-paste --type image --watch cliphist store &

# Send a notification on startup
notify-send -a aurora "hello $(whoami)" &

# Start libinput gestures, wlsunset, Telegram, and other applications
libinput-gestures-setup start &
wlsunset -S 9:00 -s 19:30 &
telegram-desktop -startintray &
rog-control-center &

# Restart xdg-desktop-portal services for Hyprland
sleep 1
killall xdg-desktop-portal-hyprland xdg-desktop-portal
/usr/lib/xdg-desktop-portal-hyprland &
sleep 2
/usr/lib/xdg-desktop-portal &
