# Shell variables
# Generated by 'wal'
wallpaper='/home/jagan/.config/hypr/wallpaper/wallpaper_84.png'

# Special
background='#090704'
foreground='#e2cebe'
cursor='#e2cebe'

# Colors
color0='#090704'
color1='#1313ae'
color2='#cf6117'
color3='#e88c35'
color4='#eb9c53'
color5='#1c80e5'
color6='#f0a681'
color7='#e2cebe'
color8='#9e9085'
color9='#1313ae'
color10='#cf6117'
color11='#e88c35'
color12='#eb9c53'
color13='#1c80e5'
color14='#f0a681'
color15='#e2cebe'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
