--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/jagan/.config/hypr/wallpaper/wallpaper_84.png"

-- Special
background="#090704"
foreground="#e2cebe"
cursor="#e2cebe"

-- Colors
color0="#090704"
color1="#1313ae"
color2="#cf6117"
color3="#e88c35"
color4="#eb9c53"
color5="#1c80e5"
color6="#f0a681"
color7="#e2cebe"
color8="#9e9085"
color9="#1313ae"
color10="#cf6117"
color11="#e88c35"
color12="#eb9c53"
color13="#1c80e5"
color14="#f0a681"
color15="#e2cebe"
